### ISSUE TITLE
accept hosts: allow migrating to different deployment

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#1281]
Hosts listed in the [`accept`](https://docs.akash.network/reference/sdl#services-expose) field are currently bound to the first deployment that uses them.  There can be only one deployment bound to an "accept" host at a time.

Currently, modifying a deployment's resources requires creating a new deployment.

To allow for zero-downtime upgrades, we should allow migrating an "accept" host to a new deployment that is owned by the same account.

The simplest workflow for this might be a manual one - add a provider command and corresponding gateway endpoint to migrate ownership of a host from one deployment to another.

```sh
akash provider hostname migrate foobar.com --dseq 10
```

The `accept` field of both `sdl` files should contain the host; it should be ignored if the host is owned by another deployment.

**Comment by hydrogen18** [comment]
For the hostname migration, consider this scenario:

1. I create a deployment (dseq 100) and it uses a host "foobar.com"
2. Later I create a deployment (dseq 200) and it uses a host "foobar.com"
3. dseq 200 comes online and is working, so I use the migrate command to move the hostname to dseq 200. 
4. At this point dseq 200 is answering requests for "foobar.com"
5. The provider is restarted

How does the provider on startup determine which dseq should hold the reservation for "foobar.com" ? Just query kubernetes Ingress objects and see where it lives presently? What if it doesn't exist in kubernetes, are we ok with the earliest dseq getting the hostname?

**Comment by boz** [comment]
> Just query kubernetes Ingress objects and see where it lives presently?

That seems reasonable.

> ok with the earliest dseq getting the hostname?

Yeah, sure.  If we happen to have the lease object then [`CreatedAt`](https://github.com/ovrclk/akash/blob/5cbf7dec4ca32340e54d6d1afbd698f34bf92bf7/x/market/types/lease.pb.go#L144)  (block height) would capture "earliest" lease a bit more accurately, but if it's not there then I don't think it's worth pulling just for this right now.

**Comment by hydrogen18** [comment]
As part of this task I am currently learning more about how kubernetes supports operators. The theory being that the hostname management responsibility possibly can be moved outside of the provider process at this time.

The plan for this is as follows

1. Remove all codes that creates or updates ingress objects from the provider
2. Create a CRD which has contains for a hostname & the kubernetes deployment to host it with
3. The provider creates (or updates) CRD instances to associate a hostname with a specific deployment
4. Create a deployment that runs a custom container image, running with a role that gives it the ability to read the custom CRDs and make any changes to the ingress objects needed to make the CRD and the ingress agree.

The core of this is an "operator", which is really just a pattern. There is no such explicit thing as a kubernetes operator in the same way there exists a kubernetes deployment or service resource. All an operator really consists of is 

1. A kubernetes role
2. RBAC entries to read, write, & modify the appropriate resources
3. Something that runs in a deployment
4. Uses a kubernetes watch to wait for a change to a resource
5. Runs code to apply that change

There are some frameworks that facilitate this, although I remain unconvinced of advantage of them at this time. This article seems to provide a reasonable overview of the relevant concepts here: https://www.infoq.com/articles/kubernetes-operators-in-depth/ . One of the constraints here is that the provider must not create multiple CRDs with the same hostname. There is no way any code can reconcile that information at this time.

There is also this project: https://github.com/jaegertracing/jaeger-operator . It's not directly relevant to us but seems to be an OK piece of reference material at this time. 

I'm working to develop a prototype that will use an operator to manage the association of ingress resources to deployments. If this works out there will also be a migration to the new way of doing things from the old one. We will need to test that process and publicize it so that the community run providers can work the same way.

**Comment by hydrogen18** [comment]
This is resolved.
