### ISSUE TITLE
x/: improve validation by parsing addresses

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#571]
In many address validations, we only check for non-empty addresses instead of validating that they are well formed.

[example](https://github.com/ovrclk/akash/blob/master/x/provider/types/msgs.go#L24):

```go
	if msg.Owner.Empty() {
		return sdkerrors.Wrap(sdkerrors.ErrInvalidAddress, "MsgCreate: Invalid Provider Address")
	}
```

This should be
```go
	if _, err := sdk.AccAddressFromBech32(msg.Owner); err != nil {
		return sdkerrors.Wrap(sdkerrors.ErrInvalidAddress, "MsgCreate: Invalid Provider Address")
	}
```

**Comment by RiccardoM** [comment]
@boz I would like to help you with this issue, however I've just checked into the current `master` code and it appears to me that the only places where the `.Empty()` form is used is when dealing with messages. 

As far as I know, an `sdk.AccAddress` object can represent either: 

1. an empty address; 
2. a valid address. 

If a user tries to send a `Msg` instance with an invalid address inside, this will not be properly parsed into an `sdk.AccAddress` object, thus failing before reaching the point in which it can be checked for emptiness. 

Also, the second code snippet should be: 

```golang
if _, err := sdk.AccAddressFromBech32(msg.Owner.String()); err != nil {
	return sdkerrors.Wrap(sdkerrors.ErrInvalidAddress, "MsgCreate: Invalid Provider Address")
}
```

Since the `AccAddressFromBech32` method accepts a `string` and not an `sdk.AccAddress` object. 

This would be pointless as the `String` method only works if the address was valid in the first place. 

In the end, I think you can close this issue safely and keep using the `Empty()` method if you are dealing with `sdk.AccAddress` objects. Otherwise, if you are dealing with addresses in the `string` format, you need to use the `AccAddressFromBech32` method.

**Comment by boz** [comment]
I see, thanks @RiccardoM.  I didn't look into this enough - `sdk.VerifyAddressFormat()` is more appropriate.

It does indeed look like `sdk.VerifyAddressFormat()` is used in `AccAddress.UnmarshalJSON()`, but given that `cosmos-sdk` is moving towards `protobuf`, I think it'd be nice to use `sdk.VerifyAddressFormat(addr)` instead of `addr.Empty()`.

**Comment by akhilkumarpilli** [comment]
@boz, To use `sdk.VerifyAddressFormat(addr)`, we need to configure sdk like [this](https://github.com/ovrclk/akash/blob/master/cmd/common/sdk.go#L19) wherever we need to change. Instead, we can keep using `Empty()` as there is no issue with it, as we are using mostly in `msgs`.

**Comment by boz** [comment]
Do we really need to do that tho?

If you use `testutil.AccAddress(t)` it will return a key with whatever prefix is configured in cosmos-sdk (default: `cosmos`).

The checks should also use whatever is configured in cosmos-sdk.

I feel like it should work fine if you use `testutil.AccAddress` to generate the addresses.

Am I missing something @akhilkumarpilli ?

**Comment by akhilkumarpilli** [comment]
No, actually we are using `Empty()` mostly in messages. If we need to replace it with `sdk.VerifyAddressFormat(addr)`, it should handle address entered from user. We can use `testutil.AccAddress(t)` for testing but not for this case. 
`sdk.VerifyAddressFormat(addr)` is failing due to address prefix differences i.e., `akash` compared with default `cosmos`.

**Comment by boz** [comment]
I still don't understand.

Shouldn't we only accept addresses with the prefix that the sdk is configured with?

On a live system, when would we want to accept an address with a `cosmos` prefix?

**Comment by akhilkumarpilli** [comment]
Sorry @boz , it's my fault. I didn't test it correctly. We don't need to configure sdk config everywhere we need to change. It will accept only addresses with prefix that the sdk is configured with. I will replace `Empty()` with `sdk.VerifyAddressFormat(addr)`. Thank you.
