### ISSUE TITLE
db performance: indexes

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#604]
We need indexes for fast look-ups of often-used queries.

Some that come to mind:

* [active orders](https://github.com/ovrclk/akash/blob/082cb048d367cadebc16de5efb592622f0de2700/x/deployment/handler/endblock.go#L16-L19)
* [active leases](https://github.com/ovrclk/akash/blob/082cb048d367cadebc16de5efb592622f0de2700/x/market/handler/endblock.go#L28-L30)
* [unmatched orders](https://github.com/ovrclk/akash/blob/082cb048d367cadebc16de5efb592622f0de2700/x/market/handler/endblock.go#L62-L64)
* [leases for provider](https://github.com/ovrclk/akash/blob/082cb048d367cadebc16de5efb592622f0de2700/client/extra.go#L9-L11) indexing bids might be better than leases.

Edit:

One option is to use prefixes to represent various states.  See [kava](https://github.com/Kava-Labs/kava) for an example

* [key](https://github.com/Kava-Labs/kava/blob/467e6f7d8b48cea93f6d6d6f1b26675e4332aed9/x/auction/types/keys.go#L30)
* [keeper](https://github.com/Kava-Labs/kava/blob/467e6f7d8b48cea93f6d6d6f1b26675e4332aed9/x/auction/keeper/keeper.go#L91-L103)

**Comment by Ropes** [comment]
Re:discovered the need for order index.

Similar to our previous indexing of data which needs quick iteration in EndBlock calls; `market` module needs an index on Orders in the Open state.

The Market module's endblock calls [WithOrders](https://github.com/ovrclk/akash/blob/98d799978399b9d2591145d0d7495d2580cc51f1/x/market/handler/endblock.go#L105). Which will iterate over all Orders, including historical ones which have long since been closed. While it has a quick exit for closed orders, it will waste a lot of time iterating in a mature blockchain.

**Comment by Ropes** [comment]
Started on the Orders Open Index, for next week:
    TODO:
    * Add/Created Open Orders to the new Index
    * Remove them when state changes
    * Implement testing

**Comment by boz** [comment]
Where are we at with this @Ropes ?
