### ISSUE TITLE
Endpoint Resource

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#867]
# Overview

Deployments that are open globally are assumed to be virtual-hosted behind a single IP, along with other tenants.  This form of multi-tenancy works okay for some classes of web applications but it falls short of supporting things like:

- UDP protocols
- Arbitrary TCP protocols
- High-performance networking

In lieu of implementing non-shared IP addresses, we can allow UDP, TCP protocols to be accessed through random ports on the provider incoming endpoints.

The user's intent to use a random port can be declared as part of an "Endpoint" resource.  The platform can then expose the user's workloads over a random port, and advertise the IP,port in the lease status API.

# Components

- [ ] SDL - declare endpoint resources
- [ ] Blockchain: affects matching, etc...
- [ ] Platform: implement `NodePort` ingresses when applicable
- [ ] Platform: expose ports via the lease status gateway API.

**Comment by hydrogen18** [comment]
I've been learning more about how Kubernetes allows exposing a service, so far it looks like the following are available

1. Ingress - we already support this, used in the examples in `_run_`
2. ClusterIP - this makes a service accessible on an internal only IP. This is possibly useful, but doesn't seem like something that is needed presently
3. LoadBalancer - dependent on the Kubernetes provider. This isn't even uniform across AWS / Azure. Supporting this doesn't seem useful because we can't count on all providers having it available or even the same thing available
4. ExternalName - This appears to be used for declaring a service external to a Kubernetes cluster
5. NodePort - This exposes a service on a port on the local node, which appears to the only option we have.

When a Kubernetes node is added, the administrator must configure the service node port range. When a service uses a port, it gets the same port number across all nodes it has associated deployments on. I suppose this was done for simplicity. A service can optionally declare a node port that is desired, but this is probably not a good idea for us. You could have two orders on the same node expecting the same port which would not work. 

So using NodePort works for exposing a service on a port, which ultimately connects through to an application. This issue is this doesn't guarantee that is accessible. Whenever a kubernetes node is running the nodeport addresses can be configured which control what address is used. This leads to two problems

1. If a provider has an external IP for each of the Kubernetes nodes, how does that fact get advertised before & after an order is filled? An order would need to make a requirement that it run on a cluster with external IPs. Then find out what IPs & ports the service can be run after the lease is won. The first part could be part of the signed attributes of a provider I think. But the second part I am unsure on.
2. IPv4 is finite and expensive to get address ranges. IPv6 is not finite but also not universally accessible. Could a provider possibly provide some sort of VPN access to the kubernetes nodes. Would this have any practicality for some use cases? How would it be isolated?

**Comment by boz** [comment]
@hydrogen18 that's exactly the situation.  nice summation.

1. We can run these workloads on nodes that have public-facing interfaces via `NodeLabels`.  Eventually-bound port number can be exposed via the lease status api in the provider gateway.
1. That would be really interesting.  I haven't thought about it much.  We should talk about this sometime.  FWIW medium-term we wanted to extend "endpoint" to optionally be a distinct IP address - our version of AWS's EIP.

**Comment by hydrogen18** [comment]
Looking at it, the NGINX ingress controller has recently added support for TCP & UDP forwarding. So it may be possible to do this without relying on NodePort functionality.

**Comment by boz** [comment]
Will it bind to a unique port for us?  That is really the issue - we need to be able to have multiple apps using the same port internally.

FWIW we used to "vhost" via TLS - if you wanted to run an arbitrary TCP port you could do it if you ran it over TLS, we'd configure hproxy to look at the SNI field to figure out the right backend to send the traffic to.

**Comment by hydrogen18** [comment]
When you say using the same port internally, do you mean inside the pod?

Yeah, I was thinking that if all exposed services worked over TLS that could make this much simpler because of the way SNI works. That would impose a couple other considerations

1. The order needs to provide a certificate for the appropriate name, this could presumably be self signed for many uses cases. We'd need to include information or automation to make that easy.
2. The DNS entry needs to get updated by someone to the IP used by the provider
3. The certificate would need to be distributed somehow in a manner only the provider has access to it.

**Comment by boz** [comment]
The containers should be agnostic to this.   Externally we can't have multitenancy behind a single port.  For http we're using the host header for routing connections.  Extending this to arbitrary protocols isn't practical.  What were left with is tls, independent IP addresses, or a port for every tenant.

For various reasons we've targeted the latter option for the MVP.   Using NodePort does a lot of the work for us - the OS chooses a port for us and k8s handles the plumbing.

**Comment by hydrogen18** [comment]
I did some more experimentation with this and confirmed

1. Default service declaration is cluster level
2. Using NodePort creates a service level IP and port, **plus** exposes the service on the node IP at the node port. Not specifying `NodePort` in the YAML definition of the service results in Kubernetes just picking a port. So this solves the conflict problem
3. You can sue NGINX to do TCP & UDP forwarding using NGINX as the ingress controller. This doesn't actually use a Service object in Kubernetes at all. You just need to specify a config map name for UDP & another for TCP when starting the ingress controller. I did this by editing the file that kind provides to start the NGINX ingress controller. In that config map you just put the external port followed by the app. name and port you want to connect to. This solves no particular problems for us, requiring us to manually maintain a mapping on external ports. The only advantage here is all traffic would flow the the ingress pod.

If we go forward with using the NodePort scheme, we'll need to document that each kubernetes node needs to have a publicly addressable IP.
