### ISSUE TITLE
validation: create deployment

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#902]
re-enable group spec validation [`here`](https://github.com/ovrclk/akash/blob/0e780fa60474dbf8b5fb752a2a630602ed96c50d/x/deployment/types/types.go#L28)

**Comment by hydrogen18** [comment]
So far I've come up with the following that needs to be done for this 


# Manifest Validation
Manifest itself is an array, so it must have at least 1 entry

## Group
- Validate Name is non non empty
- Validate Service is non empty
- Validate that at least one service has a Service that is marked as global

## Service
- Name - non empty
- Image - non empty - not latest
- Command - non empty - Why is this an array?
- Args - anything is valid
- Env - Why is this an array? Is it an array of pairs? Should be restructure it?
- Count - Length must be >1
- Expose - Length may be 0
- Resources - CPU, Storage, Memory must be nonzero

## ServiceExpose
- Port Value must be >0
- ExternalPort Value must be >0
- Proto - TCP or UDP
- Hosts - any number of entries but each one must be a valid hostname

# Manifest Cross Validation against Order
1. Only need to validate manifest against `GroupSpec`
2. `GroupSpec` resources specifies what is being leased
3. `ResourceUnits` defined in the Order must match 1-to-1 with the Manifest.
4. Manifest service with `global: false` is not counted as an endpoint since it does not consume cluster wide resources

**Comment by boz** [comment]
Note that the `CreateDeployment` transaction does not look at a manifest - it only knows about groups.

Look at the current [`validation`](https://github.com/ovrclk/akash/blob/bb5f8ea263b9de71412afb388e5c8d74f08a04cd/validation/deployment.go#L11) - among other things, it should ensure that there are no duplicate names; pricing is non-zero and in `uakt`; resource specs are within configured constraints.

the validation package attempts to validate both deployment groups and manifest groups with the same code.  this has always been cumbersome but apparently it became too cumbersome after the proto migration?

First priority is to fix validation for `CreateDeployment` because that requires a network upgrade to add later.
