### ISSUE TITLE
review pod security policy

### ISSUE THREAD

**Issue by troian** [ovrclk/akash#946]
when trying to deploy
```
d8i9f01iik9rd94h1p4b2otquv5vbff0vhnuc9tv4icps   9s          Warning   FailedCreate        replicaset/web-795598d84d      Error creating: pods "web-795598d84d-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.containers[0].securityContext.runAsNonRoot: Invalid value: false: must be true]
```

this is caused by conflict [between](https://github.com/ovrclk/akash/blob/c6a3e29889ac1b48d829231246430492e36035bd/provider/cluster/kube/builder.go#L216) [and](https://github.com/ovrclk/akash/blob/c6a3e29889ac1b48d829231246430492e36035bd/provider/cluster/kube/builder.go#L133-L133)

**Comment by boz** [comment]
refs ovrclk/operations#35

**Comment by hydrogen18** [comment]
It looks like the main things we need to do here are

1. Set it so containers do not run as root
2. Allow the provider config to specify what user ID & group ID containers should run as 
3. Require all ports described in the SDL to be >1024 on the container side, since the container won't have access to privileged ports
4. Update the demo-app container to work with this

**Comment by hydrogen18** [comment]
Putting this off for now, we've moved to gVisor to mitigate the attack surface presented
